// Configuración de Supabase
const SUPABASE_URL = 'https://mcoeobadspgxofrmkark.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_VnylL13-FwYSlPpxzPK26w_n8K49uSu';

// Configuración general
const CONFIG = {
  contratoJHOAL: '0x6A92f433471DA8c94dA4df55B090cd2b5A49317F',
  grupoTelegram: 'https://t.me/horusfaucet',
  soporteTelegram: 'https://t.me/JhoalSupportbot',
  miniAppTelegram: 'https://t.me/Jhoal_faucetbot',
  pancakeswap: 'https://pancakeswap.finance/swap?inputCurrency=0x55d398326f99059ff775485246999027b3197955&outputCurrency=0x6A92f433471DA8c94dA4df55B090cd2b5A49317F',
  bscscan: 'https://bscscan.com/token/0x6A92f433471DA8c94dA4df55B090cd2b5A49317F',
  donaciones: '0x9185F62bfd0367Db622f371b594e5579286Ea1D3',
  redDonaciones: 'BSC (BNB Smart Chain)'
};

// Traducciones
const TRANSLATIONS = {
  es: {
    subtitle: '⚱ La ofrenda del Dios Horus ⚱',
    aboutTitle: '🏛 HORUS FAUCET',
    aboutSub1: '💎 Ecosistema JHOAL Token',
    aboutSub2: '⚱ La Ofrenda del Dios Horus',
    aboutP1: 'En las tierras del Nilo, donde nace el sol y los dioses gobiernan el destino de los hombres, nació JHOAL. No es un simple token. Es la ofrenda digital que fluye por todo el ecosistema de Horus Faucet.',
    aboutP2: 'JHOAL es el token oficial de Horus Faucet, una Mini App de Telegram donde podés ganar criptomonedas GRATIS sin invertir un solo peso. No necesitás descargar nada: solo abrís el bot en Telegram, entrás a la app y empezás a ganar.',
    aboutP3: '🚰 <strong>LA FAUCET:</strong> Reclamá 1 JHOAL cada 30 minutos.<br>🎲 <strong>LOS DADOS:</strong> Apostá y multiplicá tus JHOAL hasta x10.<br>🔮 <strong>PREDICCIONES:</strong> Predecí el precio de BTC y ganá la pool.<br>🌱 <strong>HUERTO:</strong> Plantá, regá y cosechá frutos en JHOAL.',
    aboutP4: 'JHOAL no es solo una moneda. Es la llave que abre las puertas del ecosistema de Horus Faucet. Con él podés jugar, plantar, predecir, ganar y retirar a tu wallet personal (MetaMask, Trust Wallet).',
    aboutP5: 'En resumen: JHOAL es el corazón de Horus Faucet, una Mini App de Telegram que está llevando las criptomonedas a todo el mundo, gratis y sin complicaciones.',
    statsTitle: '📊 Estadísticas en Vivo',
    statsPlayers: 'Jugadores Totales',
    statsOnline: 'En Vivo Ahora',
    statsCircular: 'JHOAL Circular',
    statsBurned: 'JHOAL Quemado',
    livePrice: 'Precio en Vivo',
    btnContract: '📍 Ver Contrato',
    btnBuy: '🥞 Comprar',
    btnPancake: '🥞 Ver en PancakeSwap',
    predTitle: '🎯 Predicción de Horus',
    predDesc: '📈 Predecí el precio de BTC en 3 minutos<br>💰 Pool se reparte entre los ganadores según cercanía<br>🔥 Lo que sobra se quema cada 24h',
    btcNow: 'BTC Ahora',
    poolJHOAL: 'Pool JHOAL',
    round: 'Ronda',
    howTitle: '💰 ¿Cómo Ganar JHOAL?',
    howList: '🚰 <strong>Faucet:</strong> 1 JHOAL cada 30 minutos<br>📺 <strong>Anuncios:</strong> 5 JHOAL por video<br>🎲 <strong>Dados:</strong> Multiplicá tus JHOAL (x1.1 a x10)<br>🌱 <strong>Huerto:</strong> Plantá y cosechá frutos<br>🔮 <strong>Predicciones:</strong> Predecí el precio de BTC<br>🎁 <strong>Referidos:</strong> 1000 JHOAL por amigo',
    historyTitle: '📜 Historial Público',
    rankTitle: '🏆 Ranking Top 10',
    linksTitle: '🔗 Enlaces',
    btnPlay: '🎮 Jugar',
    btnGroup: '💬 Grupo',
    btnSupport: '📩 Soporte',
    footerContract: '📍 Contrato',
    footerPancake: '🥞 PancakeSwap',
    donate: 'Apoyá el proyecto',
    donateNote: 'Aceptamos BNB y cualquier token en la red BSC',
    disclaimer: 'JHOAL es un token de utilidad, no una inversión.',
    loading: 'Cargando...',
    noEvents: 'No hay eventos aún',
    noData: 'Sin datos aún'
  },
  en: {
    subtitle: '⚱ The offering of the God Horus ⚱',
    aboutTitle: '🏛 HORUS FAUCET',
    aboutSub1: '💎 JHOAL Token Ecosystem',
    aboutSub2: '⚱ The Offering of the God Horus',
    aboutP1: 'In the lands of the Nile, where the sun rises and the gods rule the destiny of men, JHOAL was born. It is not a simple token. It is the digital offering that flows through the entire Horus Faucet ecosystem.',
    aboutP2: 'JHOAL is the official token of Horus Faucet, a Telegram Mini App where you can earn crypto FOR FREE without investing a single penny. No download needed: just open the bot on Telegram, enter the app and start earning.',
    aboutP3: '🚰 <strong>FAUCET:</strong> Claim 1 JHOAL every 30 minutes.<br>🎲 <strong>DICE:</strong> Bet and multiply your JHOAL up to x10.<br>🔮 <strong>PREDICTIONS:</strong> Predict BTC price and win the pool.<br>🌱 <strong>GARDEN:</strong> Plant, water and harvest fruits in JHOAL.',
    aboutP4: 'JHOAL is not just a coin. It is the key that opens the doors of the Horus Faucet ecosystem. With it you can play, plant, predict, win and withdraw to your personal wallet (MetaMask, Trust Wallet).',
    aboutP5: 'In short: JHOAL is the heart of Horus Faucet, a Telegram Mini App that is bringing crypto to everyone, free and without complications.',
    statsTitle: '📊 Live Statistics',
    statsPlayers: 'Total Players',
    statsOnline: 'Online Now',
    statsCircular: 'JHOAL Circulating',
    statsBurned: 'JHOAL Burned',
    livePrice: 'Live Price',
    btnContract: '📍 View Contract',
    btnBuy: '🥞 Buy',
    btnPancake: '🥞 View on PancakeSwap',
    predTitle: '🎯 Horus Prediction',
    predDesc: '📈 Predict BTC price in 3 minutes<br>💰 Pool is split among winners by closeness<br>🔥 What is left is burned every 24h',
    btcNow: 'BTC Now',
    poolJHOAL: 'JHOAL Pool',
    round: 'Round',
    howTitle: '💰 How to Earn JHOAL?',
    howList: '🚰 <strong>Faucet:</strong> 1 JHOAL every 30 minutes<br>📺 <strong>Ads:</strong> 5 JHOAL per video<br>🎲 <strong>Dice:</strong> Multiply your JHOAL (x1.1 to x10)<br>🌱 <strong>Garden:</strong> Plant and harvest fruits<br>🔮 <strong>Predictions:</strong> Predict BTC price<br>🎁 <strong>Referrals:</strong> 1000 JHOAL per friend',
    historyTitle: '📜 Public History',
    rankTitle: '🏆 Top 10 Ranking',
    linksTitle: '🔗 Links',
    btnPlay: '🎮 Play',
    btnGroup: '💬 Group',
    btnSupport: '📩 Support',
    footerContract: '📍 Contract',
    footerPancake: '🥞 PancakeSwap',
    donate: 'Support the project',
    donateNote: 'We accept BNB and any token on the BSC network',
    disclaimer: 'JHOAL is a utility token, not an investment.',
    loading: 'Loading...',
    noEvents: 'No events yet',
    noData: 'No data yet'
  }
};
